---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    namespace: development-monitoring
    name: heartbeat-pvc
    labels:
        app: heartbeat
        
spec:
    accessModes:
    - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
    namespace: development-monitoring
    name: heartbeat-config
    labels:
        app: heartbeat
data:
    heartbeat.yml: |-
        #setup.dashboards.enabled: true
        heartbeat.config.monitors:
            path: ${path.config}/monitors.d/*.yml
            reload.enabled: false
            reload.period: 5s

        heartbeat.monitors:
        -   type: http
            urls: ["${ELASTICSEARCH_HOST}"]
            schedule: '@every 10s'
            #timeout: 16s
        #setup.template.settings:
        #    index.number_of_shards: 1
        #    index.codec: best_compression
        setup.kibana:
            host: "${KIBANA_HOST}"
        output.elasticsearch:
            hosts: ["${ELASTICSEARCH_HOST}"]
            username: ${ELASTICSEARCH_USERNAME}
            password: ${ELASTICSEARCH_PASSWORD}
        processors:
            - add_kubernetes_metadata:
                in_cluster: true
        #monitoring.enabled: true
        #monitoring.elasticsearch:
        #    hosts: ["${ELASTICSEARCH_HOST}"]
        #    username: ${ELASTICSEARCH_USERNAME}
        #    password: ${ELASTICSEARCH_PASSWORD}
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: heartbeat
    namespace: development-monitoring
    labels:
        app: heartbeat
spec:
    selector:
        matchLabels:
            app: heartbeat
    template:
        metadata:
            labels:
                app: heartbeat
        spec:
            serviceAccountName: heartbeat
            terminationGracePeriodSeconds: 30
            hostNetwork: true
            dnsPolicy: ClusterFirstWithHostNet
            containers:
            -   name: heartbeat
                image: docker.elastic.co/beats/heartbeat:7.5.1
                imagePullPolicy: Always
                args: [
                    "-c", "/etc/heartbeat.yml",
                    "-e"
                ]
                securityContext:
                    runAsUser: 0
                    capabilities:
                        add:
                        -   NET_ADMIN
                env:
                -   name: ELASTICSEARCH_HOST
                    value: kibana.development-monitoring:9200
                -   name: ELASTICSEARCH_USERNAME
                    value: elastic
                -   name: ELASTICSEARCH_PASSWORD
                    valueFrom:
                        secretKeyRef:
                            name: elasticsearch-pw-elastic
                            key: password
                -   name: KIBANA_HOST
                    value: kibana.development-monitoring
                volumeMounts:
                -   name: config
                    mountPath: /etc/heartbeat.yml
                    readOnly: true
                    subPath: heartbeat.yml
                -   name: heartbeat-persistent-storage
                    mountPath: /usr/share/heartbeat/data
            volumes:
            -   name: config
                configMap:
                    defaultMode: 0600
                    name: heartbeat-config
            -   name: heartbeat-persistent-storage
                persistentVolumeClaim:
                    claimName: heartbeat-pvc
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
    name: heartbeat
subjects:
-   kind: ServiceAccount
    name: heartbeat
    namespace: development-monitoring
roleRef:
    kind: ClusterRole
    name: heartbeat
    apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
    name: heartbeat
    labels:
        app: heartbeat
rules:
-   apiGroups: [""]
    resources:
    - nodes
    - namespaces
    - events
    - pods
    verbs: ["get", "list", "watch"]
-   apiGroups: ["extensions"]
    resources:
    - replicasets
    verbs: ["get", "list", "watch"]
-   apiGroups: ["apps"]
    resources:
    - statefulsets
    - deployments
    verbs: ["get", "list", "watch"] 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: development-monitoring
  name: heartbeat
  labels:
    app: heartbeat
---