---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    namespace: development-monitoring
    name: packetbeat-pvc
    labels:
        app: packetbeat
        
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
    namespace: development-monitoring
    name: packetbeat-config
    labels:
        app: packetbeat
data:
    packetbeat.yml: |-
        setup.dashboards.enabled: true

        setup.template:
            name: 'packetbeat'
            pattern: 'packetbeat-*'
            enabled: true

        packetbeat.interfaces.device: any

        packetbeat.protocols:
        -   type: dns
            ports: [53]
            include_authorities: true
            include_additionals: true

        -   type: http
            ports: [80,8000,8080,9200]

        -   type: mysql
            ports: [3306]
        
        -   type: redis
            ports: [6379]
            
        -   type: tls
            ports: [443, 993, 995, 5223, 8443, 8883, 9243]

        packetbeat.flows:
            timeout: 30s
            period: 10s

        processors:
        -   add_kubernetes_metadata:
                in_cluster: true

        output.elasticsearch:
            hosts: ["${ELASTICSEARCH_HOST}"]
            username: ${ELASTICSEARCH_USERNAME}
            password: ${ELASTICSEARCH_PASSWORD}
            index: packetbeat
            compression_level: 0

        setup.kibana:
            host: ${KIBANA_HOST} 
        loging:
            to_files: true
            files:
                path: /var/log/packetbeat
                name: packetbeat.log
                rotateeverybytes: 10485760 # = 10MB
                keepfiles: 7
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: packetbeat
    namespace: development-monitoring
    labels:
        app: packetbeat
spec:
    selector:
        matchLabels:
            app: packetbeat
    template:
        metadata:
            labels:
                app: packetbeat
        spec:
            serviceAccountName: packetbeat
            terminationGracePeriodSeconds: 30
            hostNetwork: true
            dnsPolicy: ClusterFirstWithHostNet
            containers:
            -   name: packetbeat
                image: docker.elastic.co/beats/packetbeat:7.5.1
                imagePullPolicy: Always
                args: [
                    "-c", "/etc/packetbeat.yml",
                    "-e"
                ]
                securityContext:
                    runAsUser: 0
                    capabilities:
                        add:
                        -   NET_ADMIN
                env:
                -   name: ELASTICSEARCH_HOST
                    value: elasticsearch-client.development-monitoring:9200
                -   name: ELASTICSEARCH_USERNAME
                    value: elastic
                -   name: ELASTICSEARCH_PASSWORD
                    valueFrom:
                        secretKeyRef:
                            name: elasticsearch-pw-elastic
                            key: password
                -   name: KIBANA_HOST
                    value: kibana.development-monitoring:5601
                resources:
                    limits:
                        memory: 200Mi
                    requests:
                        cpu: 100m
                        memory: 100Mi
                volumeMounts:
                -   name: config
                    mountPath: /etc/packetbeat.yml
                    readOnly: true
                    subPath: packetbeat.yml
                -   name: packetbeat-persistent-storage
                    mountPath: /usr/share/packetbeat/data
            volumes:
            -   name: config
                configMap:
                    defaultMode: 0600
                    name: packetbeat-config
            -   name: packetbeat-persistent-storage
                persistentVolumeClaim:
                    claimName: packetbeat-pvc
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
    name: packetbeat
subjects:
-   kind: ServiceAccount
    name: packetbeat
    namespace: development-monitoring
roleRef:
    kind: ClusterRole
    name: packetbeat
    apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
    name: packetbeat
    labels:
        app: packetbeat
rules:
-   apiGroups: [""]
    resources:
    - nodes
    - namespaces
    - events
    - pods
    verbs: ["get", "list", "watch"]
-   apiGroups: ["extensions"]
    resources:
    - replicasets
    verbs: ["get", "list", "watch"]
-   apiGroups: ["apps"]
    resources:
    - statefulsets
    - deployments
    verbs: ["get", "list", "watch"] 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: development-monitoring
  name: packetbeat
  labels:
    app: packetbeat
---