---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    namespace: staging-monitoring
    name: elasticsearch-client-pvc
    labels:
        app: elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
    namespace: staging-monitoring
    name: elasticsearch-client-config
    labels:
        app: elasticsearch
        role: client
data:
    elasticsearch.yml: |-
        cluster.name: ${CLUSTER_NAME}
        node.name: ${NODE_NAME}
        discovery.seed_hosts: ${NODE_LIST}
        cluster.initial_master_nodes: ${MASTER_NODES}

        network.host: 0.0.0.0

        node:
        master: false
        data: false
        ingest: true

        xpack.security.enabled: true
        xpack.monitoring.collection.enabled: true
        xpack.monitoring.enabled: true
        xpack.security.audit.enabled: true
---
apiVersion: v1
kind: Service
metadata:
    namespace: staging-monitoring
    name: elasticsearch-client
    labels:
        app: elasticsearch
        role: client
spec:
    type: NodePort
    ports:
    -   port: 9200
        name: client
        protocol: TCP
        targetPort: 9200
    -   port: 9300
        name: transport
    selector:
        app: elasticsearch
        role: client
---
apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: staging-monitoring
    name: elasticsearch-client
    labels:
        app: elasticsearch
        role: client
spec:
    replicas: 1
    selector:
        matchLabels:
            app: elasticsearch
            role: client
    template:
        metadata:
            labels:
                app: elasticsearch
                role: client
        spec:
            initContainers:
            -   name: sysctl-config
                image: busybox
                securityContext:
                    privileged: true
                command: ["sh","-c","sysctl -w vm.max_map_count=262144"]
            containers:
            -   name: elasticsearch-client
                image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
                resources:
                    limits:
                        cpu: 1000m
                        memory: 2000Mi
                    requests:
                        cpu: 500m
                        memory: 1000Mi
                env:
                -   name: CLUSTER_NAME
                    value: elasticsearch
                -   name: NODE_NAME
                    value: elasticsearch-client
                -   name: NODE_LIST
                    value: elasticsearch-master,elasticsearch-data,elasticsearch-client
                -   name: MASTER_NODES
                    value: elasticsearch-master
                -   name: "ES_JAVA_OPTS"
                    value:  "-Xms1024m -Xmx1024m"
                ports: 
                -   containerPort: 9200
                    name: client
                -   containerPort: 9300
                    name: transport
                volumeMounts:
                -   name: config
                    mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
                    readOnly: true
                    subPath: elasticsearch.yml
                -   name: elasticsearch-persistent-storage
                    mountPath: /data
            volumes:
            -   name: config
                configMap:
                    name: elasticsearch-client-config
            -   name: elasticsearch-persistent-storage
                persistentVolumeClaim:
                    claimName: elasticsearch-client-pvc